### PR TITLE
correct README.md

### PR DESCRIPTION
**Pull request by katsumeshi**
update the document. 
Although I have tried to declare 'civ_crop' according to the document, however got complaining  from the compiler. probably, the document is out of date.

### CODE REVIEW

**Comment by mattbajorek** [comment]
This had stumped me up too.  Like you have noted 'civ_crop' should be changed to 'crop'.

**Comment by cesards** [comment]
Sorry guys! Oh jeez I need to release a new version with all the null checks and everything else. I promise a new version this week :-/ Sorry for the bad maintenance

**Comment by cesards** [comment]
Fixed in the following release. Sorry for the delay :-/

I updated the library, samples and documentation.

**Comment by katsumeshi** [comment]
thanks for fixing up. i'm glad that no one will get stuck with same issue any more.

**Pull request merged**
